sudo: true
language: cpp
compiler: g++
script: 
 - mkdir -p $HOME/.local
 - curl -L http://www.cmake.org/files/v3.6/cmake-3.6.2-Linux-i386.tar.gz | tar -xz -C $HOME/.local --strip-components=1
 - mkdir build && cd build
 - cmake ..
 - make
